spring:
  application:
    name: provider1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_schema
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
